### PR TITLE
Add dependencies badge

### PR DESCRIPTION
**Pull request by aivus**

### CODE REVIEW

**Comment by s0ph1e** [comment]
As I can see this is only for `package.json`
Do you know something similar for `bower.json`? 
I think it would be great to have such badges for both backend and frontend dependencies

**Comment by aivus** [comment]
I found this:
https://gemnasium.com/aivus/web-scraper

By default it analyzes `bower.json` and `package.json`, but we can disable one of them.

[Dependency Status](https://gemnasium.com/aivus/web-scraper)

**Comment by s0ph1e** [comment]
Looks good 

What is better from your point of view: use both **david** and **gemnasium** or use only **gemnasium**?

**Comment by aivus** [comment]
I think we can try to use only `gemnasium` service for this repo

**Comment by s0ph1e** [comment]
ok, let's try 
Please update a PR and I'll merge it (or you can push directly to master, I've added you to collaborators)

**Pull request merged**
